import { Building2, ClipboardCheck, Handshake, MessagesSquare, ShieldCheck, Wrench } from 'lucide-react';
import { Seo } from '../components/Seo';
import { SectionHeading } from '../components/SectionHeading';
import { WhatsAppButton } from '../components/WhatsAppButton';
import { BUSINESS } from '../lib/constants';

export function AboutPage(){return <>
  <Seo title="About Mafick Integrated" description="Learn about Mafick Integrated Nig. Ltd., a Nigerian real estate and property services company built on integrity, accountability and lasting value."/>
  <section className="mx-auto grid max-w-[1440px] lg:grid-cols-2"><div className="flex flex-col justify-center bg-[#17352C] px-5 py-20 text-white sm:px-10 lg:px-14"><p className="mb-4 font-bold text-[#D3AC67]">About Mafick Integrated</p><h1 className="font-display text-5xl leading-none sm:text-7xl">Built to make property ownership and management simpler.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/70">We are a Nigerian real estate and property services company providing coordinated solutions for individuals, organisations, investors, landlords and property owners.</p></div><img className="min-h-[500px] h-full w-full object-cover" src="/images/property-development-consultation.webp" alt="Mafick Integrated property professionals reviewing development plans in Lagos"/></section>
  <section className="mx-auto grid max-w-[1200px] gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:py-28"><SectionHeading kicker="Our business" title="Professional support from property opportunity to long-term asset care."/><div className="space-y-6 text-lg leading-8 text-[#59635E]"><p>Our work covers property sourcing, marketing, buying and selling, management, maintenance, renovation, development coordination and advisory support. This breadth allows clients to work with one responsive company while specialised activities are coordinated around a clear property objective.</p><p>We maintain transparent communication with property owners, buyers, tenants, investors, contractors and other stakeholders. Inspection updates, quotations, maintenance schedules, transaction information and project progress are organised to support accountability and timely decisions.</p><p>Every engagement begins with an agreed scope. Where legal, valuation, structural or other specialist verification is required, the appropriate qualified professionals are coordinated and responsibilities remain clearly defined.</p><div className="border-l-4 border-[#C1913D] bg-[#E8EDE8] p-6 text-sm leading-6"><strong className="block text-[#17352C]">Registered company</strong>{BUSINESS.registration}</div></div></section>
  <section className="bg-white py-20 lg:py-28"><div className="mx-auto max-w-[1200px] px-5 sm:px-8"><SectionHeading kicker="What guides our work" title="Integrity, professionalism and lasting value."/><div className="mt-12 grid border-y border-[#AEB8B1] md:grid-cols-3">{[[ShieldCheck,'Integrity','We communicate honestly, protect client interests and distinguish confirmed facts from matters that still require verification.'],[MessagesSquare,'Responsive communication','Property reports, consultations, schedules and progress information are provided in a clear and practical form.'],[ClipboardCheck,'Accountability','Scopes, responsibilities, approvals and completion expectations are established to keep people and projects aligned.']].map(([Icon,title,text],i)=><article key={String(title)} className={`py-8 md:px-7 ${i<2?'border-b md:border-b-0 md:border-r border-[#D5DBD6]':''}`}>{typeof Icon!=='string'&&<Icon className="text-[#8B4A35]"/>}<h3 className="mt-7 font-display text-3xl text-[#17352C]">{String(title)}</h3><p className="mt-3 leading-7 text-[#59635E]">{String(text)}</p></article>)}</div></div></section>
  <section className="bg-[#E8EDE8] py-20"><div className="mx-auto max-w-[1200px] px-5 sm:px-8"><SectionHeading kicker="Our professional network" title="The right expertise, coordinated around the property." intro="Our service network supports delivery across planning, construction, maintenance, inspection and facility operations."/><div className="mt-10 grid gap-px bg-[#B9C4BC] sm:grid-cols-2 lg:grid-cols-4">{[[Building2,'Architects & engineers','Design, technical coordination and development support.'],[Wrench,'Artisans & contractors','Repairs, maintenance, renovation and specialist trades.'],[ClipboardCheck,'Property professionals','Inspection, valuation and transaction-process support.'],[Handshake,'Facility service providers','Cleaning, landscaping, security and estate operations.']].map(([Icon,title,text])=><article key={String(title)} className="bg-white p-7">{typeof Icon!=='string'&&<Icon className="text-[#8B4A35]"/>}<h3 className="mt-7 font-display text-2xl text-[#17352C]">{String(title)}</h3><p className="mt-3 text-sm leading-6 text-[#59635E]">{String(text)}</p></article>)}</div></div></section>
  <section className="mx-auto grid max-w-[1200px] gap-10 px-5 py-20 sm:px-8 lg:grid-cols-2 lg:py-28"><div className="border-t-4 border-[#C1913D] pt-7"><p className="font-bold text-[#8B4A35]">Our vision</p><h2 className="mt-4 font-display text-4xl text-[#17352C]">To become a trusted and leading real estate and property services company across the Nigerian property market.</h2></div><div className="border-t-4 border-[#17352C] pt-7"><p className="font-bold text-[#8B4A35]">Our mission</p><h2 className="mt-4 font-display text-4xl text-[#17352C]">To simplify property ownership, investment, development and maintenance through transparent, value-driven solutions.</h2></div></section>
  <section className="bg-[#8B4A35] px-5 py-16 text-white"><div className="mx-auto flex max-w-[1100px] flex-col justify-between gap-6 md:flex-row md:items-center"><div><h2 className="font-display text-4xl sm:text-5xl">Let us understand the property objective.</h2><p className="mt-3 text-white/75">Our team will recommend a practical next step and the right service scope.</p></div><WhatsAppButton className="bg-[#17352C]" label="Speak with our team"/></div></section>
  </>}
