import { ClipboardCheck, MessagesSquare, Search, ShieldCheck, UserRound } from 'lucide-react';
import { Seo } from '../components/Seo';
import { SectionHeading } from '../components/SectionHeading';
import { WhatsAppButton } from '../components/WhatsAppButton';
import { BUSINESS } from '../lib/constants';

export function AboutPage(){return <>
  <Seo title="About Mafick Integrated" description="Learn about Mafick Integrated Nig. Ltd., a Nigerian real estate and property services company built on integrity, accountability and lasting value."/>
  <section className="mx-auto grid max-w-[1440px] lg:grid-cols-2"><div className="flex flex-col justify-center bg-[#17352C] px-5 py-20 text-white sm:px-10 lg:px-14"><p className="mb-4 font-bold text-[#D3AC67]">About Mafick Integrated</p><h1 className="font-display text-5xl leading-none sm:text-7xl">A practical property company for real decisions and lasting value.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/70">Mafick Integrated supports homeowners, buyers, investors, landlords and organisations with the work required to find, market, improve and care for property in Nigeria.</p></div><img className="min-h-[500px] h-full w-full object-cover" src="/images/property-development-consultation.webp" alt="Nigerian property professionals reviewing development plans"/></section>
  <section className="mx-auto grid max-w-[1200px] gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:py-28"><SectionHeading kicker="Who we are" title="Property work is easier when communication and responsibility are clear."/><div className="space-y-6 text-lg leading-8 text-[#59635E]"><p>We provide real estate, property marketing, property management and property development support across the property lifecycle. Our role may begin with a search or listing and continue through inspection, negotiation, documentation coordination, maintenance, renovation or ongoing management.</p><p>Clients receive straightforward updates on what has been confirmed, what still needs professional verification and what action is required next. That means clearer inspections, quotations, maintenance schedules, transaction updates and project progress reports.</p><p>Where legal, valuation, architectural, engineering or other specialist work is required, the need is explained and the appropriate professional involvement is agreed for that specific assignment.</p><div className="border-l-4 border-[#C1913D] bg-[#E8EDE8] p-6 text-sm leading-6"><strong className="block text-[#17352C]">Our company</strong>{BUSINESS.registration}</div></div></section>
  <section className="bg-white py-20 lg:py-28"><div className="mx-auto max-w-[1200px] px-5 sm:px-8"><SectionHeading kicker="What guides our work" title="Integrity, professionalism and lasting value."/><div className="mt-12 grid border-y border-[#AEB8B1] md:grid-cols-3">{[[ShieldCheck,'Integrity','We communicate honestly, protect client interests and distinguish confirmed facts from matters that still require verification.'],[MessagesSquare,'Responsive communication','Property reports, consultations, schedules and progress information are provided in a clear and practical form.'],[ClipboardCheck,'Accountability','Scopes, responsibilities, approvals and completion expectations are established to keep people and projects aligned.']].map(([Icon,title,text],i)=><article key={String(title)} className={`py-8 md:px-7 ${i<2?'border-b md:border-b-0 md:border-r border-[#D5DBD6]':''}`}>{typeof Icon!=='string'&&<Icon className="text-[#8B4A35]"/>}<h3 className="mt-7 font-display text-3xl text-[#17352C]">{String(title)}</h3><p className="mt-3 leading-7 text-[#59635E]">{String(text)}</p></article>)}</div></div></section>
  <section className="bg-[#E8EDE8] py-20"><div className="mx-auto max-w-[1200px] px-5 sm:px-8"><SectionHeading kicker="How we work" title="A clear process from first conversation to follow-through." intro="The exact scope changes with the property, but every assignment is organised around the same four responsibilities."/><div className="mt-10 grid gap-px bg-[#B9C4BC] sm:grid-cols-2 lg:grid-cols-4">{[[MessagesSquare,'Understand the brief','We define the property, objective, location, timing, budget and information already available.'],[Search,'Inspect and review','We coordinate the appropriate property inspection and identify questions that require verification.'],[ClipboardCheck,'Agree the scope','The proposed service, responsibilities, costs, approvals and expected deliverables are made clear.'],[ShieldCheck,'Coordinate and report','We provide practical updates, records and next steps throughout the assignment.']].map(([Icon,title,text])=><article key={String(title)} className="bg-white p-7">{typeof Icon!=='string'&&<Icon className="text-[#8B4A35]"/>}<h3 className="mt-7 font-display text-2xl text-[#17352C]">{String(title)}</h3><p className="mt-3 text-sm leading-6 text-[#59635E]">{String(text)}</p></article>)}</div></div></section>
  <section className="bg-white py-20 lg:py-28"><div className="mx-auto max-w-[1200px] px-5 sm:px-8"><SectionHeading kicker="Meet our team" title="The people behind Mafick Integrated." intro="Team names, positions, photographs and short profiles can be added here as they are approved."/><div className="mt-12 grid gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4">{[['Leadership & strategy','01'],['Property marketing','02'],['Property operations','03'],['Client services','04']].map(([role,number])=><article key={role}><div className="relative grid aspect-[4/5] place-items-center overflow-hidden bg-[#D9DEDA] text-[#89918C]" role="img" aria-label="Team profile photo placeholder"><UserRound size={92} strokeWidth={1}/><span className="absolute bottom-4 right-4 font-display text-4xl text-[#A7AFAA]">{number}</span></div><p className="mt-5 font-display text-2xl text-[#17352C]">Team member name</p><p className="mt-1 text-sm font-bold text-[#8B4A35]">{role}</p></article>)}</div></div></section>
  <section className="mx-auto grid max-w-[1200px] gap-10 px-5 py-20 sm:px-8 lg:grid-cols-2 lg:py-28"><div className="border-t-4 border-[#C1913D] pt-7"><p className="font-bold text-[#8B4A35]">Our vision</p><h2 className="mt-4 font-display text-4xl text-[#17352C]">To become a trusted and leading real estate and property services company across the Nigerian property market.</h2></div><div className="border-t-4 border-[#17352C] pt-7"><p className="font-bold text-[#8B4A35]">Our mission</p><h2 className="mt-4 font-display text-4xl text-[#17352C]">To simplify property ownership, investment, development and maintenance through transparent, value-driven solutions.</h2></div></section>
  <section className="bg-[#8B4A35] px-5 py-16 text-white"><div className="mx-auto flex max-w-[1100px] flex-col justify-between gap-6 md:flex-row md:items-center"><div><h2 className="font-display text-4xl sm:text-5xl">Let us understand the property objective.</h2><p className="mt-3 text-white/75">Our team will recommend a practical next step and the right service scope.</p></div><WhatsAppButton className="bg-[#17352C]" label="Speak with our team"/></div></section>
  </>}
