import { FormEvent, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { MessageCircle, Phone } from 'lucide-react';
import { Seo } from '../components/Seo';
import { WHATSAPP_DISPLAY, whatsappUrl } from '../lib/constants';

type Errors={name?:string;phone?:string;interest?:string;message?:string};
export function ContactPage() {
  const [params]=useSearchParams(); const listing=params.get('listing');
  const initial=useMemo(()=>listing?`We would like more information about ${listing}. Please share the current availability and next steps.`:'',[listing]);
  const [errors,setErrors]=useState<Errors>({}); const [fallback,setFallback]=useState('');
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);const name=String(data.get('name')||'').trim();const phone=String(data.get('phone')||'').trim();const interest=String(data.get('interest')||'').trim();const message=String(data.get('message')||'').trim();const next:Errors={};if(name.length<2)next.name='Please enter the name our team should use when responding.';if(!/^\+?[0-9\s()-]{8,18}$/.test(phone))next.phone='Enter a reachable phone number with at least 8 digits, including country code if outside Nigeria.';if(!interest)next.interest='Select the service area that best matches the request.';if(message.length<10)next.message='Please add the property type, location, objective or required service.';setErrors(next);if(Object.keys(next).length)return;const email=String(data.get('email')||'').trim();const formatted=`Hello Mafick Integrated.\nName: ${name}\nPhone: ${phone}${email?`\nEmail: ${email}`:''}\nService required: ${interest}\nMessage: ${message}`;const url=whatsappUrl(formatted);setFallback(url);window.open(url,'_blank','noopener,noreferrer');}
  return <>
    <Seo title="Contact" description="Contact Mafick Integrated for property marketing, management, maintenance, renovation, development or advisory services."/>
    <section className="bg-[#17352C] px-5 py-16 text-white sm:px-8 lg:py-24"><div className="mx-auto max-w-[1200px]"><p className="mb-4 font-bold text-[#D3AC67]">Contact Mafick Integrated</p><h1 className="font-display text-5xl sm:text-7xl">How can our team support the property?</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/70">Provide the property type, location, objective and preferred timeline. The form prepares a clear WhatsApp message and does not store the submitted information.</p></div></section>
    <section className="mx-auto grid max-w-[1240px] gap-12 px-5 py-16 sm:px-8 lg:grid-cols-[.72fr_1.28fr] lg:py-24"><aside><h2 className="font-display text-4xl text-[#17352C]">Speak with our team directly</h2><p className="mt-4 leading-7 text-[#59635E]">Call or send a WhatsApp message with a concise description of the property requirement. A team member will respond with the most useful next step.</p><a href="tel:+2348158475918" className="mt-7 flex items-center gap-3 border-y border-[#AEB8B1] py-5 font-bold text-[#17352C]"><Phone className="text-[#8B4A35]"/>{WHATSAPP_DISPLAY}</a><a href={whatsappUrl()} target="_blank" rel="noreferrer" className="mt-5 inline-flex min-h-12 items-center gap-2 bg-[#1f8f54] px-6 font-bold text-white"><MessageCircle/>Call or WhatsApp our team</a><div className="mt-10 border-l-4 border-[#C1913D] bg-[#E8EDE8] p-5 text-sm leading-6 text-[#59635E]"><strong className="text-[#17352C]">Helpful information:</strong> property type, location, current condition, required service, budget range and preferred timeline.</div></aside>
      <form onSubmit={submit} noValidate className="border-t-4 border-[#C1913D] bg-white p-6 sm:p-10"><div className="grid gap-6 sm:grid-cols-2"><Field label="Name" error={errors.name}><input className="form-control" name="name" autoComplete="name" aria-invalid={!!errors.name}/></Field><Field label="Phone number" error={errors.phone}><input className="form-control" name="phone" type="tel" autoComplete="tel" placeholder="+234 800 000 0000" aria-invalid={!!errors.phone}/></Field></div><div className="mt-6 grid gap-6 sm:grid-cols-2"><Field label="Email (optional)"><input className="form-control" name="email" type="email" autoComplete="email"/></Field><Field label="Service required" error={errors.interest}><select className="form-control" name="interest" defaultValue="" aria-invalid={!!errors.interest}><option value="" disabled>Choose one</option><option>Property marketing or sale</option><option>Property purchase or sourcing</option><option>Property management</option><option>Maintenance or repairs</option><option>Cleaning or facility services</option><option>Inspection or advisory</option><option>Renovation or property improvement</option><option>Architectural or development support</option><option>Other property service</option></select></Field></div><div className="mt-6"><Field label="Property requirement" error={errors.message}><textarea className="form-control min-h-36 resize-y" name="message" defaultValue={initial} aria-invalid={!!errors.message}/></Field></div><button className="mt-7 inline-flex min-h-12 items-center gap-2 bg-[#17352C] px-7 font-bold text-white hover:bg-[#244A3B]" type="submit"><MessageCircle size={19}/>Continue in WhatsApp</button>{fallback&&<div role="status" className="mt-6 border-l-4 border-[#1f8f54] bg-[#E8EDE8] p-5"><strong className="text-[#17352C]">Opening WhatsApp…</strong><p className="mt-1 text-sm text-[#59635E]">If it did not open, <a className="font-bold underline" href={fallback} target="_blank" rel="noreferrer">continue here</a>.</p></div>}</form></section>
  </>;
}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label className="block text-sm font-bold text-[#17352C]">{label}<span className="mt-2 block">{children}</span>{error&&<span className="mt-2 block text-sm font-medium text-[#9B352C]">{error}</span>}</label>}
