import { Link, useParams } from 'react-router-dom';
import { CheckCircle2, MapPin } from 'lucide-react';
import { getListing, listingSpecs, listings } from '../data/listings';
import { ListingCard } from '../components/ListingCard';
import { Seo } from '../components/Seo';
import { WhatsAppButton } from '../components/WhatsAppButton';

export function ListingDetailPage() {
  const {slug}=useParams(); const listing=getListing(slug);
  if(!listing) return <section className="mx-auto max-w-3xl px-5 py-24 text-center"><h1 className="font-display text-5xl text-[#17352C]">Listing not found</h1><p className="mt-4 text-[#59635E]">The property may have been removed or the address may be incorrect.</p><Link to="/listings" className="mt-8 inline-flex bg-[#17352C] px-6 py-3 font-bold text-white">Return to listings</Link></section>;
  const related=listings.filter(x=>x.propertyType===listing.propertyType&&x.slug!==listing.slug).concat(listings.filter(x=>x.propertyType!==listing.propertyType&&x.slug!==listing.slug)).slice(0,3);
  const specs=listingSpecs(listing);
  return <>
    <Seo title={listing.title} description={`${listing.price}. ${listing.description}`}/>
    <section className="mx-auto max-w-[1440px] px-5 pb-10 pt-8 sm:px-8 lg:px-12"><Link to="/listings" className="text-sm font-bold text-[#8B4A35]">Back to all listings</Link><div className={`mt-6 grid gap-3 ${listing.images.length>1?'lg:grid-cols-[1.55fr_.75fr]':''}`}><img className="h-[360px] w-full object-cover sm:h-[560px]" src={listing.images[0]} alt={listing.title}/>{listing.images.length>1&&<div className="grid grid-cols-2 gap-3 lg:grid-cols-1">{listing.images.slice(1,3).map((image,i)=><img key={image} src={image} alt={`${listing.title} view ${i+2}`} className="h-full min-h-[170px] w-full object-cover"/>)}</div>}</div>{listing.imageNote&&<p className="mt-3 text-xs leading-5 text-[#68736D]">{listing.imageNote}</p>}</section>
    <section className="mx-auto grid max-w-[1280px] gap-12 px-5 py-12 sm:px-8 lg:grid-cols-[1fr_380px] lg:py-16"><div><p className="flex items-center gap-2 text-sm font-bold text-[#8B4A35]"><MapPin size={16}/>{listing.location}</p><h1 className="mt-3 font-display text-5xl leading-none text-[#17352C] sm:text-6xl">{listing.title}</h1><p className="mt-5 text-3xl font-extrabold">{listing.price}</p><div className="mt-8 grid border-y border-[#AEB8B1] sm:grid-cols-3">{specs.map(spec=><div key={spec} className="border-b border-[#D5DBD6] py-4 text-sm font-bold capitalize sm:border-b-0 sm:border-r sm:px-4 first:pl-0 last:border-r-0">{spec}</div>)}</div><h2 className="mt-10 font-display text-3xl text-[#17352C]">Property overview</h2><p className="mt-4 max-w-3xl text-lg leading-8 text-[#59635E]">{listing.description}</p>{listing.pricing&&<><h2 className="mt-10 font-display text-3xl text-[#17352C]">Price options</h2><div className="mt-5 grid gap-px bg-[#C4CCC6] sm:grid-cols-2">{listing.pricing.map(option=><div key={option.label} className="bg-white p-5"><p className="text-sm font-bold text-[#68736D]">{option.label}</p><p className="mt-1 text-xl font-extrabold text-[#17352C]">{option.value}</p></div>)}</div></>}{listing.paymentPlan&&<div className="mt-5 border-l-4 border-[#C1913D] bg-[#F2EEE5] p-5"><strong className="text-[#17352C]">Payment plan</strong><p className="mt-1 text-sm leading-6 text-[#59635E]">{listing.paymentPlan}</p></div>}{listing.titleDocument&&<div className="mt-8 border-y border-[#D5DBD6] py-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#8B4A35]">Title document stated</p><p className="mt-2 font-bold text-[#17352C]">{listing.titleDocument}</p></div>}<h2 className="mt-10 font-display text-3xl text-[#17352C]">Key features</h2><ul className="mt-5 grid gap-3 sm:grid-cols-2">{listing.features.map(feature=><li key={feature} className="flex gap-2 text-sm font-semibold text-[#4F5B55]"><CheckCircle2 size={17} className="mt-0.5 shrink-0 text-[#8B4A35]"/>{feature}</li>)}</ul>{listing.nearby&&<><h2 className="mt-10 font-display text-3xl text-[#17352C]">Nearby landmarks</h2><p className="mt-2 text-sm leading-6 text-[#68736D]">The property information supplied identifies proximity to the following locations:</p><ul className="mt-5 grid gap-3 sm:grid-cols-2">{listing.nearby.map(place=><li key={place} className="flex gap-2 text-sm font-semibold text-[#4F5B55]"><MapPin size={17} className="mt-0.5 shrink-0 text-[#8B4A35]"/>{place}</li>)}</ul></>}<div className="mt-8 border-l-4 border-[#C1913D] bg-[#E8EDE8] p-6"><h3 className="font-bold text-[#17352C]">Before commitment</h3><p className="mt-2 text-sm leading-6 text-[#59635E]">Availability, ownership, title, condition, dimensions, landmark distances and transaction terms should be confirmed through inspection and the appropriate professional verification process.</p></div></div>
      <aside className="h-fit border-t-4 border-[#C1913D] bg-[#17352C] p-7 text-white lg:sticky lg:top-28"><p className="font-display text-3xl">Request property details</p><p className="mt-3 text-sm leading-6 text-white/70">Our team will confirm availability, share the current information and coordinate an inspection where appropriate.</p><WhatsAppButton className="mt-6 w-full bg-[#1f8f54]" message={`Hello Mafick Integrated, we would like more information about ${listing.title}. Please confirm availability and inspection details.`} label="Inquire on WhatsApp"/><Link className="mt-3 flex min-h-11 items-center justify-center border border-white/35 px-4 text-sm font-bold hover:bg-white hover:text-[#17352C]" to={`/contact?listing=${encodeURIComponent(listing.title)}`}>Use the full contact form</Link></aside></section>
    <section className="bg-white py-20"><div className="mx-auto max-w-[1280px] px-5 sm:px-8"><h2 className="font-display text-4xl text-[#17352C]">Related properties</h2><div className="mt-9 grid gap-7 md:grid-cols-3">{related.map(x=><ListingCard key={x.slug} listing={x}/>)}</div></div></section>
  </>;
}
