import { Building2, Check, ClipboardCheck, Hammer, Paintbrush, Search, ShieldCheck, Sparkles, Trees, Wrench } from 'lucide-react';
import { Seo } from '../components/Seo';
import { SectionHeading } from '../components/SectionHeading';
import { WhatsAppButton } from '../components/WhatsAppButton';

const marketing = ['Residential, commercial and industrial property marketing','Digital and social media property promotion','Property listing, advertising and market positioning','Property photography and promotional presentation','Buyer and tenant lead coordination','Sales strategy and transaction communication'];
const transactions = ['Sourcing houses, land and real estate assets','Residential, commercial and industrial property sales','Land and house brokerage services','Property inspection and viewing coordination','Documentation-process assistance','Buyer and seller representation and negotiation'];
const management = ['Routine supervision and property monitoring','Tenant and occupant coordination','Condition inspection and assessment','Preventive and corrective maintenance planning','Artisan, contractor and service-provider coordination','Property records and maintenance reporting'];

function OfferList({items}:{items:string[]}) { return <ul className="grid gap-4 sm:grid-cols-2">{items.map(item=><li key={item} className="flex gap-3 border-t border-[#D5DBD6] pt-4 leading-6 text-[#4F5B55]"><Check className="mt-1 shrink-0 text-[#8B4A35]" size={18}/>{item}</li>)}</ul>; }

const supportServices = [
  {icon:Wrench,title:'Property maintenance & repairs',text:'General building maintenance, plumbing, electrical repairs, air-conditioning service, painting, carpentry, tiling, masonry, roofing and minor structural work.'},
  {icon:Sparkles,title:'Cleaning & facility services',text:'Routine and deep cleaning, post-construction cleaning, office and residential cleaning, compound care, waste coordination and environmental upkeep.'},
  {icon:ClipboardCheck,title:'Inspection, review & advisory',text:'Condition assessment, inspection reporting, investment guidance, valuation coordination, market assessment and recommendations for property improvement.'},
  {icon:Building2,title:'Architectural & development support',text:'Architectural coordination, space planning, project supervision, contractor management and property development planning and execution support.'},
  {icon:Paintbrush,title:'Renovation & property improvement',text:'Interior and exterior renovation, decoration, refurbishment, kitchen and bathroom upgrades, flooring, ceilings, partitions and beautification.'},
  {icon:Trees,title:'Facility & estate support',text:'Facility inspections, preventive planning, landscaping, security coordination, generator and mechanical maintenance, plus material procurement support.'},
];

export function ServicesPage() {
  return <>
    <Seo title="Real Estate & Property Services" description="Property marketing, buying, management, maintenance, cleaning, advisory, renovation and development support from Mafick Integrated."/>
    <section className="bg-[#17352C] px-5 py-20 text-white sm:px-8 lg:py-28"><div className="mx-auto max-w-[1200px]"><p className="mb-4 font-bold text-[#D3AC67]">Our services</p><h1 className="max-w-4xl font-display text-5xl leading-none sm:text-7xl">Professional support across the property lifecycle.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/70">Mafick Integrated serves individuals, corporate organisations, investors, landlords and property owners through coordinated real estate, management, maintenance, development and advisory solutions.</p></div></section>

    <section className="mx-auto grid max-w-[1440px] gap-14 px-5 py-20 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:px-12 lg:py-28">
      <div><Search className="text-[#8B4A35]" size={38}/><SectionHeading className="mt-7" kicker="Market visibility" title="Property marketing & promotion" intro="We position property clearly, present it professionally and coordinate the communication required to reach buyers and tenants."/><img src="/images/hero-lekki-estate.webp" className="mt-9 aspect-[4/3] w-full object-cover" alt="Residential property in a Nigerian estate marketed by Mafick Integrated"/></div>
      <div className="lg:pt-20"><h2 className="font-display text-3xl text-[#17352C]">Our marketing scope</h2><div className="mt-6"><OfferList items={marketing}/></div><div className="mt-10 border-l-4 border-[#C1913D] bg-[#E8EDE8] p-6"><h3 className="font-display text-2xl text-[#17352C]">Corporate communication throughout</h3><p className="mt-2 leading-7 text-[#59635E]">Clients receive responsive consultation, listing updates, inspection schedules, enquiry feedback and transaction communication designed to keep expectations aligned.</p></div><WhatsAppButton className="mt-7" message="Hello Mafick Integrated, we would like to discuss property marketing and promotion." label="Discuss property marketing"/></div>
    </section>

    <section className="bg-white py-20 lg:py-28"><div className="mx-auto grid max-w-[1440px] gap-14 px-5 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:px-12"><div className="order-2 lg:order-1"><Building2 className="text-[#8B4A35]" size={38}/><SectionHeading className="mt-7" kicker="Acquisition & disposal" title="Property buying & sales" intro="We support the search, presentation, inspection and transaction process for houses, land, apartments and commercial assets."/><h3 className="mt-10 font-display text-3xl text-[#17352C]">Transaction support</h3><div className="mt-6"><OfferList items={transactions}/></div><h3 className="mt-10 font-display text-3xl text-[#17352C]">From brief to transaction</h3><ol className="mt-6 border-l border-[#AEB8B1]">{[['Consultation','We define objectives, budget, location, timing and available property information.'],['Sourcing or positioning','We identify suitable opportunities or prepare the client property for the market.'],['Inspection and review','We coordinate physical inspection and the appropriate independent professional checks.'],['Negotiation and documentation','We support communication, negotiation and transaction-process coordination through closing.']].map(([title,text],i)=><li key={title} className="relative pb-7 pl-8"><span className="absolute -left-4 top-0 grid h-8 w-8 place-items-center rounded-full bg-[#C1913D] font-bold text-white">{i+1}</span><h4 className="font-bold text-[#17352C]">{title}</h4><p className="mt-1 text-sm leading-6 text-[#59635E]">{text}</p></li>)}</ol><WhatsAppButton className="mt-5" message="Hello Mafick Integrated, we would like support with a property purchase or sale." label="Discuss buying or selling"/></div><img src="/images/property-development-consultation.webp" className="order-1 min-h-[560px] w-full object-cover lg:order-2" alt="Nigerian property professionals coordinating a real estate project"/></div></section>

    <section className="mx-auto grid max-w-[1440px] gap-14 px-5 py-20 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:px-12 lg:py-28"><img src="/images/property-maintenance-team.webp" alt="Nigerian facility maintenance team inspecting a managed property" className="h-full min-h-[560px] w-full object-cover"/><div><ShieldCheck className="text-[#8B4A35]" size={38}/><SectionHeading className="mt-7" kicker="Asset care" title="Property management services" intro="We help property owners maintain oversight, coordinate occupants and service providers, and preserve the condition and operational value of their assets."/><div className="mt-8"><OfferList items={management}/></div><div className="mt-10 grid gap-5 sm:grid-cols-2"><div className="border-t-2 border-[#8B4A35] pt-5"><h4 className="font-bold text-[#17352C]">Owner visibility</h4><p className="mt-2 text-sm leading-6 text-[#59635E]">Inspection findings, maintenance recommendations, quotations and activity updates are communicated clearly.</p></div><div className="border-t-2 border-[#8B4A35] pt-5"><h4 className="font-bold text-[#17352C]">Operational coordination</h4><p className="mt-2 text-sm leading-6 text-[#59635E]">Occupants, artisans, contractors and scheduled services are coordinated around approved priorities.</p></div></div><WhatsAppButton className="mt-8" message="Hello Mafick Integrated, we would like to discuss property management services." label="Discuss property management"/></div></section>

    <section className="bg-[#E8EDE8] py-20 lg:py-28"><div className="mx-auto max-w-[1300px] px-5 sm:px-8"><SectionHeading kicker="Property support services" title="Specialist coordination for maintenance, improvement and development." intro="These services can be engaged independently or combined under a broader property-management or development scope."/><div className="mt-12 grid gap-px bg-[#B9C4BC] md:grid-cols-2 lg:grid-cols-3">{supportServices.map(({icon:Icon,title,text})=><article key={title} className="bg-[#F7F8F5] p-7"><Icon className="text-[#8B4A35]"/><h3 className="mt-8 font-display text-3xl leading-tight text-[#17352C]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#59635E]">{text}</p><WhatsAppButton compact className="mt-6" message={`Hello Mafick Integrated, we would like to discuss ${title.toLowerCase()}.`} label="Request a consultation"/></article>)}</div></div></section>

    <section className="mx-auto max-w-[1000px] px-5 py-20 sm:px-8 lg:py-28"><SectionHeading kicker="Common questions" title="Clear answers before work begins."/><div className="mt-10 divide-y divide-[#C5CEC7] border-y border-[#C5CEC7]">{[
      ['Can Mafick Integrated manage only part of a property project?','Yes. Services can be scoped individually—for example inspection, marketing, renovation coordination or routine management—or combined into an end-to-end engagement.'],
      ['Do clients create and manage their own listings?','No. Property information is submitted directly to our team. We review, prepare and publish approved listings, then coordinate enquiries and inspections.'],
      ['Does the website accept property payments?','No. The website provides information and captures enquiries. Verification, documentation, professional checks and transactions are coordinated outside the website.'],
      ['Can the company support property owners outside Nigeria?','Yes. We can coordinate inspections, reports, maintenance activity, project updates and scheduled consultations for diaspora property owners.'],
      ['How are quotations and project updates handled?','The agreed scope determines the reporting format. Clients may receive quotations, schedules, inspection reports, progress photographs, maintenance records and completion updates.'],
    ].map(([q,a])=><details key={q} className="group py-6"><summary className="cursor-pointer list-none pr-8 font-display text-2xl text-[#17352C] marker:hidden">{q}<span className="float-right font-sans text-[#8B4A35] group-open:rotate-45">+</span></summary><p className="mt-4 max-w-3xl leading-7 text-[#59635E]">{a}</p></details>)}</div></section>
  </>;
}
